import dynamic from "next/dynamic";

import Link from "next/link";
import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Table2, HardDrive, GitBranch, Layers, Lightbulb, Database, FileCode, ArrowRight } from "lucide-react";
import { CommonMistakes, type Mistake } from "@/components/common-mistakes";
import { AnimatedFlow, type FlowStep } from "@/components/animated-flow";
const DatabaseHeroViz = dynamic(
  () => import("./_components/database-hero-viz").then(m => m.DatabaseHeroViz),
  { loading: () => <div className="h-64 rounded-lg bg-muted animate-pulse" /> }
);

import { ScrollReveal } from "@/components/scroll-reveal";
import { Separator } from "@/components/ui/separator";

const topics = [
  {
    href: "/database/sqlalchemy-models",
    label: "SQLAlchemy Models",
    icon: Table2,
    description: "Define tables, column types, and relationships using SQLAlchemy ORM.",
  },
  {
    href: "/database/sessions",
    label: "Database Sessions",
    icon: HardDrive,
    description: "Engine setup, SessionLocal, and the get_db() yield dependency pattern.",
  },
  {
    href: "/database/alembic-migrations",
    label: "Alembic Migrations",
    icon: GitBranch,
    description: "Version control your database schema with autogenerated migrations.",
  },
  {
    href: "/database/crud-operations",
    label: "CRUD Operations",
    icon: Layers,
    description: "Repository pattern for create, read, update, delete with SQLAlchemy.",
  },
];

const flowSteps: FlowStep[] = [
  { id: "models", label: "Define Models", description: "Create Python classes that map to database tables using SQLAlchemy ORM.", icon: <Table2 className="size-5" />, color: "cyan-500" },
  { id: "migrate", label: "Create Migration", description: "Alembic compares your models to the database and generates a migration script.", icon: <GitBranch className="size-5" />, color: "cyan-500" },
  { id: "apply", label: "Apply Migration", description: "Run alembic upgrade head to apply the schema changes to your database.", icon: <Database className="size-5" />, color: "teal-500" },
  { id: "session", label: "Get Session", description: "Use Depends(get_db) to inject a database session into your endpoint.", icon: <HardDrive className="size-5" />, color: "teal-500" },
  { id: "crud", label: "CRUD Operations", description: "Query, create, update, and delete records using the session.", icon: <Layers className="size-5" />, color: "cyan-500" },
];

const mistakes: Mistake[] = [
  {
    title: "Not closing database sessions",
    subtitle: "Creating sessions without cleanup",
    wrongCode: `@app.get("/users")
def list_users():
    db = SessionLocal()  # Session created
    users = db.query(User).all()
    return users
    # Session never closed — connection leaks!`,
    rightCode: `@app.get("/users")
def list_users(db: Session = Depends(get_db)):
    # get_db() uses yield + finally: db.close()
    return db.query(User).all()
    # Session always closed after response`,
    filename: "main.py",
    explanation: "Always use the get_db() dependency with yield/finally to ensure sessions are closed. Creating sessions manually without cleanup leaks database connections under load.",
  },
  {
    title: "Using create_all() in production",
    subtitle: "Skipping migrations for convenience",
    wrongCode: `# main.py — DON'T do this in production
from database import Base, engine

Base.metadata.create_all(bind=engine)  # ← Only creates
# Can't track changes, can't rollback, no migration history`,
    rightCode: `# Use Alembic instead:
# alembic revision --autogenerate -m "initial"
# alembic upgrade head
#
# create_all() is fine for tests:
# Base.metadata.create_all(bind=test_engine)`,
    filename: "main.py",
    explanation: "create_all() only creates tables that don't exist — it can't alter existing tables. Use Alembic migrations for production to track schema changes, support rollbacks, and maintain a version history.",
  },
];

export default function DatabasePage() {
  return (
    <div className="max-w-4xl ambient-database">
      <div className="h-1 w-20 rounded-full bg-gradient-to-r from-cyan-500 to-teal-500 mb-8" />

      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <h1 className="text-3xl font-serif italic">Database</h1>
          <Badge variant="secondary">4 topics</Badge>
        </div>
        <p className="text-muted-foreground text-lg max-w-2xl">
          The complete database workflow for FastAPI — define models with SQLAlchemy,
          manage sessions with dependency injection, version your schema with Alembic,
          and build clean CRUD operations.
        </p>
      </div>

      <ScrollReveal className="mb-8">
        <DatabaseHeroViz />
      </ScrollReveal>

      <div className="rounded-lg glass border-cyan-500/20 p-4 mb-8">
        <div className="flex gap-3">
          <Lightbulb className="size-5 text-cyan-500 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-medium mb-1">Tip</p>
            <p className="text-sm text-muted-foreground">
              FastAPI pairs naturally with SQLAlchemy for ORM, Alembic for
              migrations, and dependency injection for session management.
              Together they form a complete, production-ready database layer.
            </p>
          </div>
        </div>
      </div>

      <ScrollReveal className="mb-8">
        <h2 className="text-lg font-semibold mb-4">The Database Workflow</h2>
        <AnimatedFlow steps={flowSteps} accentColor="cyan" />
      </ScrollReveal>

      <Separator className="my-8" />

      <div className="grid gap-4 sm:grid-cols-2 mb-12">
        {topics.map((topic) => (
          <Link key={topic.href} href={topic.href}>
            <Card className="group h-full transition-all duration-300 hover:shadow-md hover:-translate-y-0.5 cursor-pointer border-border/50 hover:border-border">
              <CardHeader>
                <div className="flex items-center gap-2">
                  <topic.icon className="size-4 text-cyan-500" />
                  <CardTitle className="text-base">{topic.label}</CardTitle>
                </div>
                <CardDescription>{topic.description}</CardDescription>
              </CardHeader>
            </Card>
          </Link>
        ))}
      </div>

      <CommonMistakes mistakes={mistakes} />
    </div>
  );
}
