"use client";

import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { CodeBlock } from "@/components/code-block";
import { ScrollReveal } from "@/components/scroll-reveal";
import { TextEffect } from "@/components/ui/text-effect";
import { CommonMistakes, type Mistake } from "@/components/common-mistakes";

const mistakes: Mistake[] = [
  {
    title: "Not adding type hints to parameters",
    subtitle: "Missing types means the docs can't show parameter details",
    wrongCode: `@app.get("/items/{item_id}")
async def get_item(item_id):  # No type hint!
    return {"item_id": item_id}
# Docs show item_id as "string" with no validation`,
    rightCode: `@app.get("/items/{item_id}")
async def get_item(item_id: int):  # Typed!
    return {"item_id": item_id}
# Docs show item_id as "integer" with auto-validation`,
    filename: "main.py",
    explanation: "FastAPI uses type hints to generate accurate documentation AND validate input. Without types, the docs are vague and there's no automatic validation.",
  },
  {
    title: "Disabling docs in development",
    subtitle: "Setting docs_url=None while still building the API",
    wrongCode: `app = FastAPI(
    docs_url=None,   # Disabled!
    redoc_url=None,  # Also disabled!
)
# Now you can't test endpoints interactively`,
    rightCode: `import os

app = FastAPI(
    docs_url="/docs" if os.getenv("ENV") != "production" else None,
    redoc_url="/redoc" if os.getenv("ENV") != "production" else None,
)
# Docs available in dev, hidden in production`,
    filename: "main.py",
    explanation: "Only disable docs in production. During development, /docs is your best friend for testing endpoints. Use environment variables to control visibility per environment.",
  },
];

export default function AutoGeneratedDocsPage() {
  return (
    <div className="max-w-4xl ambient-fundamentals">
      <div className="mb-10">
        <div className="flex items-center gap-3 mb-3">
          <h1 className="text-3xl font-bold">Auto-Generated Docs</h1>
          <Badge variant="outline">Fundamentals</Badge>
        </div>
        <TextEffect
          preset="fade-in-blur"
          per="word"
          delay={0.1}
          className="text-lg text-muted-foreground max-w-2xl"
        >
          FastAPI automatically generates interactive API documentation from your code — no extra setup required.
        </TextEffect>
      </div>

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">FastAPI&apos;s Killer Feature</h2>
          <p className="text-muted-foreground mb-4">
            Most frameworks require you to write API documentation separately from your code. FastAPI flips this: it automatically generates interactive, up-to-date documentation directly from your endpoint definitions, type hints, and Pydantic models.
          </p>
          <p className="text-muted-foreground">
            Just write your endpoints and the docs appear. Every parameter, request body, response model, and status code is documented automatically. No extra work, no drift between code and docs.
          </p>
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Swagger UI (/docs)</h2>
          <p className="text-muted-foreground mb-4">
            Swagger UI is available at <code className="text-sm bg-muted px-1.5 py-0.5 rounded">/docs</code> by default. It provides an interactive interface where you can explore all your endpoints, see their parameters, try them out with real requests, and inspect the responses — all from your browser.
          </p>
          <CodeBlock
            code={`uvicorn main:app --reload
# Open browser: http://localhost:8000/docs`}
            filename="terminal"
          />
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">ReDoc (/redoc)</h2>
          <p className="text-muted-foreground mb-4">
            ReDoc is an alternative documentation UI available at <code className="text-sm bg-muted px-1.5 py-0.5 rounded">/redoc</code>. It presents the same API information in a cleaner, more readable layout that&apos;s better suited for browsing and reading through documentation. Same data, different presentation — use whichever you prefer.
          </p>
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Customizing the Docs</h2>
          <p className="text-muted-foreground mb-4">
            You can customize the documentation title, description, version, and even the URLs where they&apos;re served. Set <code className="text-sm bg-muted px-1.5 py-0.5 rounded">docs_url=None</code> to disable Swagger UI entirely if needed.
          </p>
          <CodeBlock
            code={`from fastapi import FastAPI

app = FastAPI(
    title="My Awesome API",
    description="A production-ready API built with FastAPI",
    version="1.0.0",
    docs_url="/docs",        # Swagger UI (default)
    redoc_url="/redoc",      # ReDoc (default)
    # docs_url=None,         # Disable Swagger UI
)`}
            filename="main.py"
          />
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Adding Descriptions to Endpoints</h2>
          <p className="text-muted-foreground mb-4">
            Use the <code className="text-sm bg-muted px-1.5 py-0.5 rounded">summary</code> parameter and Python docstrings to add rich descriptions to your endpoints. These appear directly in the generated documentation.
          </p>
          <CodeBlock
            code={`@app.get("/items/{item_id}", summary="Get a single item", tags=["Items"])
async def get_item(item_id: int):
    """
    Retrieve an item by its ID.

    - **item_id**: The unique identifier of the item
    """
    return {"item_id": item_id}`}
            filename="main.py"
          />
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section>
          <h2 className="text-2xl font-semibold mb-4">Key Points</h2>
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-lg border p-4">
              <p className="text-sm font-medium mb-1">/docs for Swagger UI</p>
              <p className="text-xs text-muted-foreground">Interactive documentation with a &quot;Try it out&quot; button for live testing</p>
            </div>
            <div className="rounded-lg border p-4">
              <p className="text-sm font-medium mb-1">/redoc for ReDoc</p>
              <p className="text-xs text-muted-foreground">Clean, readable alternative documentation layout</p>
            </div>
            <div className="rounded-lg border p-4">
              <p className="text-sm font-medium mb-1">Customize via FastAPI() Params</p>
              <p className="text-xs text-muted-foreground">Set title, description, version, and doc URLs on the app instance</p>
            </div>
            <div className="rounded-lg border p-4">
              <p className="text-sm font-medium mb-1">Docstrings Become Descriptions</p>
              <p className="text-xs text-muted-foreground">Python docstrings on endpoint functions appear in the generated docs</p>
            </div>
          </div>
        </section>
      </ScrollReveal>

      <CommonMistakes mistakes={mistakes} />
    </div>
  );
}
