"use client";

import dynamic from "next/dynamic";

import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { CodeBlock } from "@/components/code-block";
import { ScrollReveal } from "@/components/scroll-reveal";
import { TextEffect } from "@/components/ui/text-effect";
import { CommonMistakes, type Mistake } from "@/components/common-mistakes";
import { RoughHighlight } from "@/components/rough-highlight";
import { AutoAnimateGrid } from "@/components/auto-animate-grid";
const DocsPreviewViz = dynamic(
  () => import("../_components/docs-preview-viz").then(m => m.DocsPreviewViz),
  { ssr: false, loading: () => <div className="h-64 rounded-lg bg-muted animate-pulse" /> }
);
import { WhatCouldGoWrong } from "@/components/what-could-go-wrong";
import { ConversationalCallout } from "@/components/conversational-callout";
import { SimpleFlow } from "@/components/simple-flow";
import { WhatYouJustLearned } from "@/components/what-you-just-learned";
import { MentalModelChallenge } from "@/components/mental-model-challenge";
import { AhaMoment } from "@/components/aha-moment";

const mistakes: Mistake[] = [
  {
    title: "Not adding type hints to parameters",
    subtitle: "Missing types means the docs can't show parameter details",
    wrongCode: `@app.get("/items/{item_id}")
async def get_item(item_id):  # No type hint!
    return {"item_id": item_id}
# Docs show item_id as "string" with no validation`,
    rightCode: `@app.get("/items/{item_id}")
async def get_item(item_id: int):  # Typed!
    return {"item_id": item_id}
# Docs show item_id as "integer" with auto-validation`,
    filename: "main.py",
    explanation: "FastAPI uses type hints to generate accurate documentation AND validate input. Without types, the docs are vague and there's no automatic validation.",
  },
  {
    title: "Disabling docs in development",
    subtitle: "Setting docs_url=None while still building the API",
    wrongCode: `app = FastAPI(
    docs_url=None,   # Disabled!
    redoc_url=None,  # Also disabled!
)
# Now you can't test endpoints interactively`,
    rightCode: `import os

app = FastAPI(
    docs_url="/docs" if os.getenv("ENV") != "production" else None,
    redoc_url="/redoc" if os.getenv("ENV") != "production" else None,
)
# Docs available in dev, hidden in production`,
    filename: "main.py",
    explanation: "Only disable docs in production. During development, /docs is your best friend for testing endpoints. Use environment variables to control visibility per environment.",
  },
];

export default function AutoGeneratedDocsPage() {
  return (
    <div className="max-w-4xl ambient-fundamentals">
      <div className="mb-10">
        <div className="flex items-center gap-3 mb-3">
          <h1 className="text-3xl font-bold">Auto-Generated Docs</h1>
          <Badge variant="outline">Fundamentals</Badge>
        </div>
        <TextEffect
          preset="fade-in-blur"
          per="word"
          delay={0.1}
          className="text-lg text-muted-foreground max-w-2xl"
        >
          &quot;Where are the docs?&quot; &quot;Read the code.&quot; That conversation ends careers. FastAPI makes sure it never has to happen.
        </TextEffect>
      </div>

      {/* 1. Failure hook */}
      <WhatCouldGoWrong
        scenario="You hand a frontend developer your API. They ask: 'Where are the docs?' You say: 'Read the code.' They stare at you. This collaboration is going nowhere."
        error={`GET /docs → 200 OK\n\n[Empty Swagger UI with no endpoints documented]\n\nvs.\n\nGET /docs → 200 OK\n\n[Rich Swagger UI: 15 endpoints, request/response schemas, examples, auth flows]`}
        errorType="Missing Docs"
        accentColor="rose"
        className="mb-8"
      />

      {/* 2. Bridge from failure to concept */}
      <ConversationalCallout type="question" className="mb-8">
        <p>
          What if your docs wrote themselves? What if every time you added an endpoint, the documentation updated automatically — with the right parameters, the right types, and a &quot;Try it out&quot; button? That&apos;s not a fantasy. That&apos;s what FastAPI does out of the box.
        </p>
      </ConversationalCallout>

      {/* 3. Mental model BEFORE code */}
      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">How FastAPI Generates Docs</h2>
          <p className="text-muted-foreground mb-4">
            FastAPI reads your Python code — your type hints, Pydantic models, and endpoint decorators — and automatically generates an OpenAPI schema. That schema powers two interactive documentation UIs.
          </p>
          <SimpleFlow
            steps={[
              { label: "Type Hints", detail: "int, str, List[Item]" },
              { label: "Pydantic Model", detail: "Request/response shapes" },
              { label: "OpenAPI Schema", detail: "JSON spec (auto-generated)" },
              { label: "Swagger UI / ReDoc", detail: "Interactive docs", status: "success" },
            ]}
            accentColor="rose"
            className="mb-4"
          />
        </section>
      </ScrollReveal>

      {/* 4. Checkpoint */}
      <WhatYouJustLearned
        points={[
          "FastAPI generates documentation from your code — no extra files to maintain",
          "Type hints and Pydantic models are the source of truth for your docs",
          "You get two UIs for free: Swagger UI (/docs) and ReDoc (/redoc)",
        ]}
        section="How docs work"
        className="mb-8"
      />

      <Separator className="my-8" />

      {/* 5. FastAPI's killer feature */}
      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Why This Is FastAPI&apos;s Killer Feature</h2>
          <p className="text-muted-foreground mb-4">
            Most frameworks make you write docs separately from your code. That means your docs are always slightly out of date. Someone adds a parameter and forgets to update the docs. Someone changes a response shape and the docs still show the old one.
          </p>
          <p className="text-muted-foreground mb-4">
            FastAPI flips this: it <RoughHighlight type="highlight" color="#f43f5e">automatically generates</RoughHighlight> interactive, up-to-date documentation directly from your endpoint definitions, <RoughHighlight type="underline" color="#f43f5e">type hints</RoughHighlight>, and Pydantic models. <RoughHighlight type="box" color="#f43f5e">No extra work, no drift between code and docs.</RoughHighlight>
          </p>
        </section>
      </ScrollReveal>

      <AhaMoment
        setup="So when I add a type hint to a parameter, it shows up in both the validation AND the docs?"
        reveal="Exactly! That's the magic of FastAPI's design. A single type hint does three things: it validates incoming data, it generates documentation, and it gives you IDE autocomplete. Write it once, get three benefits. This is why FastAPI is obsessed with type hints — they're not just for code quality, they're the engine that drives everything."
        className="mb-8"
      />

      <Separator className="my-8" />

      {/* Interactive visualization (KEEP as-is) */}
      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Preview: Code to Docs</h2>
          <p className="text-muted-foreground mb-4">See how Python type hints automatically become interactive Swagger UI documentation.</p>
          <DocsPreviewViz />
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Swagger UI (/docs)</h2>
          <p className="text-muted-foreground mb-4">
            This is your go-to during development. It&apos;s available at <code className="text-sm bg-muted px-1.5 py-0.5 rounded">/docs</code> by default, and it lets you explore endpoints, see parameters, send real requests, and inspect responses — all from your browser. No Postman needed.
          </p>
          <CodeBlock
            code={`# Start your app
uvicorn main:app --reload

# Open your browser to:
# http://localhost:8000/docs
#
# You'll see every endpoint, every parameter,
# and a "Try it out" button for each one.`}
            filename="terminal"
          />
        </section>
      </ScrollReveal>

      <ConversationalCallout type="insight" className="mb-8">
        <p>
          Pro tip: share the <code className="text-sm bg-muted px-1.5 py-0.5 rounded">/docs</code> URL with your frontend team. They can test your endpoints, see exactly what shape the data comes in, and even generate client code from it. It&apos;s way better than a Slack message saying &quot;the endpoint returns a list of objects.&quot;
        </p>
      </ConversationalCallout>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">ReDoc (/redoc)</h2>
          <p className="text-muted-foreground mb-4">
            ReDoc is the other documentation UI, available at <code className="text-sm bg-muted px-1.5 py-0.5 rounded">/redoc</code>. Same data, cleaner layout. It&apos;s better for reading through your API documentation top to bottom. Some teams use Swagger for testing and ReDoc for sharing.
          </p>
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Customizing Your Docs</h2>
          <p className="text-muted-foreground mb-4">
            You can customize the title, description, version, and even the URLs. Want to disable docs in production? Set the URL to <code className="text-sm bg-muted px-1.5 py-0.5 rounded">None</code>.
          </p>
          <CodeBlock
            code={`from fastapi import FastAPI

app = FastAPI(
    title="My Awesome API",
    description="A production-ready API built with FastAPI",
    version="1.0.0",
    docs_url="/docs",        # Swagger UI (default)
    redoc_url="/redoc",      # ReDoc (default)
    # docs_url=None,         # Set to None to disable
)`}
            filename="main.py"
          />
        </section>
      </ScrollReveal>

      <Separator className="my-8" />

      <ScrollReveal>
        <section className="mb-10">
          <h2 className="text-2xl font-semibold mb-4">Making Your Docs Actually Useful</h2>
          <p className="text-muted-foreground mb-4">
            Auto-generated docs are great. But you can make them <em>amazing</em> by adding descriptions, summaries, and examples. FastAPI pulls all of this from your Python code — docstrings, parameter descriptions, everything.
          </p>
          <CodeBlock
            code={`@app.get(
    "/items/{item_id}",
    summary="Get a single item",  # Shows in the endpoint list
    tags=["Items"],               # Groups endpoints in the sidebar
)
async def get_item(item_id: int):
    """
    Retrieve an item by its ID.

    - **item_id**: The unique identifier of the item

    Returns the full item object including price and tags.
    """
    return {"item_id": item_id}

# Your docstring becomes the detailed description in Swagger UI.
# Markdown formatting works!`}
            filename="main.py"
          />
        </section>
      </ScrollReveal>

      <WhatYouJustLearned
        points={[
          "Swagger UI (/docs) is interactive — you can test endpoints right from the browser",
          "ReDoc (/redoc) is better for reading — same data, cleaner layout",
          "Docstrings and summaries make your auto-generated docs genuinely useful",
          "You can disable docs in production with docs_url=None",
        ]}
        section="Using the docs"
        className="mb-8"
      />

      <Separator className="my-8" />

      {/* Mental Model Challenge */}
      <MentalModelChallenge
        question="If you add a description parameter to your Pydantic field, where exactly does it appear in Swagger UI?"
        options={[
          { label: "Only in the endpoint's parameter list", correct: false, explanation: "Field descriptions show up in the schema section, not the parameter list (those come from Query/Path descriptions)." },
          { label: "In the Schema section and the request body example", correct: true, explanation: "Right! Pydantic Field descriptions map to OpenAPI's schema field descriptions." },
          { label: "Nowhere — Pydantic descriptions are only for Python code", correct: false, explanation: "FastAPI extracts everything from Pydantic and maps it to OpenAPI. Nothing is wasted." },
          { label: "In the response section only", correct: false, explanation: "If the model is used as a request body, the description appears in the request schema too." },
        ]}
        hint="Think about where Pydantic models show up in the OpenAPI spec..."
        answer="It appears in the Schema section at the bottom of Swagger UI, next to the field name in the model definition. It also shows up in the request body example when you click 'Try it out'. FastAPI extracts these from Field(description='...') and maps them directly to OpenAPI's field descriptions."
        className="mb-8"
      />

      <Separator className="my-8" />

      <AhaMoment
        setup="Does this mean if I write good Pydantic models with descriptions, I basically never need to write separate API documentation?"
        reveal="Pretty much, yes. That's the whole point. Your code IS your documentation. Well-typed endpoints with descriptive Pydantic models generate docs that are always accurate and always up to date. Some teams even generate client SDKs from the OpenAPI schema — so your type hints end up powering the frontend's TypeScript types too."
        className="mb-8"
      />

      <Separator className="my-8" />

      {/* Key Points grid (KEEP existing) */}
      <ScrollReveal>
        <section>
          <h2 className="text-2xl font-semibold mb-4">Key Points</h2>
          <AutoAnimateGrid className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-lg border p-4 transition-colors hover:border-rose-500/30 hover:bg-rose-500/5">
              <p className="text-sm font-medium mb-1">/docs for Swagger UI</p>
              <p className="text-xs text-muted-foreground">Interactive documentation with a &quot;Try it out&quot; button for live testing</p>
            </div>
            <div className="rounded-lg border p-4 transition-colors hover:border-rose-500/30 hover:bg-rose-500/5">
              <p className="text-sm font-medium mb-1">/redoc for ReDoc</p>
              <p className="text-xs text-muted-foreground">Clean, readable alternative documentation layout</p>
            </div>
            <div className="rounded-lg border p-4 transition-colors hover:border-rose-500/30 hover:bg-rose-500/5">
              <p className="text-sm font-medium mb-1">Customize via FastAPI() Params</p>
              <p className="text-xs text-muted-foreground">Set title, description, version, and doc URLs on the app instance</p>
            </div>
            <div className="rounded-lg border p-4 transition-colors hover:border-rose-500/30 hover:bg-rose-500/5">
              <p className="text-sm font-medium mb-1">Docstrings Become Descriptions</p>
              <p className="text-xs text-muted-foreground">Python docstrings on endpoint functions appear in the generated docs</p>
            </div>
          </AutoAnimateGrid>
        </section>
      </ScrollReveal>

      {/* CommonMistakes (KEEP existing) */}
      <CommonMistakes mistakes={mistakes} />
    </div>
  );
}
