import type { Metadata } from "next";
export const metadata: Metadata = { title: "Alembic Migrations", description: "Version control your database schema with autogenerated migrations using Alembic." };
export default function Layout({ children }: { children: React.ReactNode }) { return children; }
